version: '3'

services:
  db:
    image: mysql:8.0
    #image: mysql:latest
    container_name: fops-db
    restart: unless-stopped
    #restart: no
    env_file: .env
    environment:
      - MYSQL_DATABASE=fops-wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network